q_list = [ 'Whats your full name?',
'How old are you?',
'Whats your Birthday?',
'What starsign does that make it?',
'Whats your favourite colour?',
'Whats your lucky number?',
'Do you have any pets?',
'Where are you from?',
'How tall are you?',
'What shoe size are you?',
'How many pairs of shoes do you own?',
'If you were prime miniser/ruler of the world what laws would you make?',
'If you were a super hero what powers would you have?',
'and what would your hero name be?',
'and what outfit would you wear?',
'What was your last dream about?',
'What would you do if you won the lottery?',
'Would you like to build/design your own house?',
'Which form of public transport do you prefer?',
'What talents do you have?',
'Can you juggle?',
'Can you solve a rubix cube?',
'Do you have a cherished childhood teddybear?',
'Are you psychic in any way?',
'Are you a good dancer?',
'Are you a good singer?',
'Are you a good cook?',
'Are you a good artist?',
'Are you a good listener?',
'Are you a good public speaker?',
'Are you a good babysitter?',
'Are you a good mechanic?',
'Are you a good diplomat?',
'Are you a good employee?',
'Are you a good dresser?',
'Are you a good swimmer?',
'Are you a good skier?',
'Are you a good lover?',
'Are you a good musician?',
'Are you a good comedian?',
'Are you a good cleaner?',
'Are you a good actor?',
'Are you a good writer?',
'Have you ever been bungee jumping?',
'Have you ever been canoeing/kayaking?',
'What types of holidays do you prefer?',
'Whats the furthest you\'ve ever been on holiday?',
'What was your favourite holiday?',
'Where would your dream holiday be?',
'Can you tap dance?',]
